# config.toml
base_url = "https://ivanmaieli.github.io"
title = "Ivan Maieli"
description = "Systems Engineer"
default_language = "en"
compile_sass = false
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "solarized-light"

[extra]
author = "Ivan Maieli"
bio = "Systems Engineer focused on real-time systems, autonomous vehicles, and rocketry."
email = "ivan.maieli@gmail.com"
github = "github.com/IvanMaieli"
linkedin = "linkedin.com/in/ivan-maieli"